_BASE_: "../base_clip_frozen_image_r50.yaml"
MODEL:
  WEIGHTS: "projects/PartGLEE/checkpoint/PartGLEE_RN50.pth"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 531
  MaskDINO:
    NUM_OBJECT_QUERIES: 300
    NUM_PART_QUERIES: 10
    UNIFY_OBJECT_PART: True
    Q_FORMER: True
    OBJECT_PART_DECODER_LAYERS: 6
DATASETS:
  TRAIN: ("partimagenet_train",)
  TEST: ("partimagenet_val",)
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005
  STEPS: (6000, )
  MAX_ITER: 10000
  CHECKPOINT_PERIOD: 2000
TEST:
  EVAL_PERIOD: 2000
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "joint_image_lsj"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
OUTPUT_DIR: projects/PartGLEE/output/Inference/partimagenet_RN50/