_BASE_: "../../base_clip_frozen_image_r50.yaml"
MODEL:
  META_ARCHITECTURE: "PartGLEE"
  USE_EARLYFUSION: True
  WEIGHTS: "projects/PartGLEE/checkpoint/PartGLEE_RN50.pth"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 531
  MaskDINO:
    NUM_OBJECT_QUERIES: 300
    NUM_PART_QUERIES: 10
    UNIFY_OBJECT_PART: True
    Q_FORMER: True
    OBJECT_PART_DECODER_LAYERS: 6
DATASETS:
  TRAIN: ("pascal_voc_train_segm", "pascal_part_base_train", )
  TEST: ("pascal_part_open_vocabulary_val", )
SOLVER:
  IMS_PER_BATCH: 16
  BASE_LR: 0.00005
  STEPS: (12000, 16000,)
  MAX_ITER: 20000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "joint_image_lsj"
DATALOADER:
  SAMPLER_TRAIN: "MultiDatasetSampler"
  DATASET_RATIO: [1, 2]
  USE_DIFF_BS_SIZE: True
  DATASET_BS: [1, 1]
  USE_RFS: [False, False]
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 8
OUTPUT_DIR: projects/PartGLEE/output/Inference/pascal_part_RN50/