_BASE_: "../base_clip_frozen_image_r50.yaml"
MODEL:
  WEIGHTS: "projects/PartGLEE/checkpoint/PartGLEE_RN50.pth"
  SEM_SEG_HEAD:
    NAME: "MaskDINOHead"
    IGNORE_VALUE: 255
    NUM_CLASSES: 531
  MaskDINO:
    NUM_OBJECT_QUERIES: 300
    NUM_PART_QUERIES: 10
    UNIFY_OBJECT_PART: True
    Q_FORMER: True
    OBJECT_PART_DECODER_LAYERS: 6
DATASETS:
  TEST: ('seginw_Airplane-Parts_val', 'seginw_Bottles_val', 'seginw_Brain-Tumor_val', 'seginw_Chicken_val', 'seginw_Cows_val', 'seginw_Electric-Shaver_val', 'seginw_Elephants_val', 'seginw_Fruits_val', 'seginw_Garbage_val', 'seginw_Ginger-Garlic_val', 'seginw_Hand_val', 'seginw_Hand-Metal_val', 'seginw_House-Parts_val', 'seginw_HouseHold-Items_val', 'seginw_Nutterfly-Squireel_val', 'seginw_Phones_val', 'seginw_Poles_val', 'seginw_Puppies_val', 'seginw_Rail_val', 'seginw_Salmon-Fillet_val', 'seginw_Strawberry_val', 'seginw_Tablets_val', 'seginw_Toolkits_val', 'seginw_Trash_val', 'seginw_Watermelon_val')
SOLVER:
  IMS_PER_BATCH: 8
  BASE_LR: 0.00005
  STEPS: (60000, )
  MAX_ITER: 90000
  CHECKPOINT_PERIOD: 5000
TEST:
  EVAL_PERIOD: 5000
INPUT:
  IMAGE_SIZE: 1024
  MIN_SCALE: 0.1
  MAX_SCALE: 2.0
  FORMAT: "RGB"
  DATASET_MAPPER_NAME: "joint_image_lsj"
DATALOADER:
  FILTER_EMPTY_ANNOTATIONS: True
  NUM_WORKERS: 4
OUTPUT_DIR: projects/PartGLEE/output/Inference/SeginW-RN50/